apiVersion: v1
kind: Service
metadata:
  name: ec2-operator
  labels:
    app: ec2-operator
spec:
  type: ClusterIP
  selector:
    app: ec2-operator
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-operator
spec:
  selector:
    matchLabels:
      app: ec2-operator
  replicas: 2
  template:
    metadata:
      labels:
        app: ec2-operator
    spec:
      containers:
        - name: ec2-operator
          image: rahul67/ec2-operator:v0.7
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 512Mi
